### ISSUE TITLE
[BUG] Console spam Console spam [Server thread/DEBUG] [co.mi.pm.ev.ArsCompatEventHandler/]: Changing mana from

### ISSUE THREAD

**Issue by ProsperCraft** [XxInvictus/PMMOBridge#3]
https://github.com/baileyholl/Ars-Nouveau/issues/721

**Comment by XxInvictus** [comment]
Update currently in Processing on Curseforge which removes this spam, though this is only in debug log which is... for the purpose of debugging. It is slightly unreasonable to complain about excess logging in a debug log, I would expect complaints if it was latest log.
