### ISSUE TITLE
[BUG] Client crashes

### ISSUE THREAD

**Issue by HollishKid** [XxInvictus/PMMOBridge#4]
**Describe the bug**
When even I attempt to throw a spell my client crashes. This specifically happens with an empty spellbook.

**To Reproduce**
Take an empty spell book in hand and right-click.

**Game Details:**
 - MC Version: 1.16.5
 - Forge Version: 36.2.39
 - PMMO Bridge Version: 1.0.7
 - PMMO Version: 3.67.7
 
 This is the crash report: https://pastebin.com/h7tSbJWn

**Comment by XxInvictus** [comment]
I just submitted an update to Curseforge, should be approved after not too long. I am not sure of exact cause as I have only updated dependencies and could not replicate this issue when I was testing those changes. Might be one of the deprecated Ars functions.
